

- name: "settings"
  label: "Settings"
  files:
    - file: "src/pages/settings/header.md"
      label: "Header Navigation"
      name: "header-navigation"
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "headerNavigation",
          }
        - {
          label: "Header Navigation",
          name: "headerNavigation",
          widget: "list",
          default: [],
          fields: [
            { label: Label, name: label, widget: string, default: '' },
            { label: Url, name: url, widget: string, default: '' },
            {
              label: Sub Menu,
              name: subMenu,
              widget: list,
              required: false,
              fields: [
                { label: Label, name: label, widget: string, default: '' },
                { label: Url, name: url, widget: string, default: '' }
              ]
            }
          ]
        }
    - file: "src/pages/settings/login.md"
      label: "Login"
      name: "login"
      fields:
        - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "login",
          }
        - {
          label: "Login",
          name: "login",
          widget: "object",
          default: [],
          fields: [
            { label: Action, name: action, widget: string, default: '' },
            { label: Method, name: method, widget: string, default: '' },
            { label: Placeholder, name: placeholder, widget: string, default: '' },
            { label: Button text, name: buttonText, widget: string, default: '' },
          ]
        }
