backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "themes"
    label: "Theme Template"
    folder: "src/pages/themes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "theme",
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Preview Link", name: "previewHref", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
            label: Sections,
            name: sections,
            widget: list,
            collapsed: true,
            summary: "{{fields.hero.sectionName}}{{fields.features.sectionName}}{{fields.themes.sectionName}}{{fields.supports.sectionName}}{{fields.zigzag.sectionName}}",
            fields: [
              {
                label: Hero,
                name: hero,
                widget: object,
                collapsed: true,
                summary: "{{fields.sectionName}}",
                required: false,
                fields: [
                  { label: Section name, name: sectionName, widget: string, required: false },
                  { label: Disable, name: disable, widget: boolean, required: false },
                  { label: Heading, name: heading, widget: string, required: false },
                  { label: Description, name: description, widget: text, required: false },
                ]
              },
              {
                label: Features,
                name: features,
                widget: object,
                collapsed: true,
                summary: "{{fields.sectionName}}",
                required: false,
                fields: [
                  { label: Section name, name: sectionName, widget: string, required: false },
                  { label: Disable, name: disable, widget: boolean, required: false },
                  { label: Heading, name: heading, widget: string, required: false },
                  { label: Description, name: description, widget: text, required: false },
                  {
                    label: Decorate,
                    name: decorate,
                    widget: select,
                    required: false,
                    options: [
                      { label: "None", value: "" },
                      { label: "Decorate 1", value: "type1" },
                      { label: "Decorate 2", value: "type2" }
                    ]
                  },
                  {
                    label: Body,
                    name: body,
                    widget: list,
                    required: false,
                    fields: [
                      { label: Image, name: image, widget: image },
                      { label: Title, name: title, widget: string },
                      { label: Description, name: description, widget: text },
                    ]
                  }
                ]
              },
              {
                label: Themes,
                name: themes,
                widget: object,
                collapsed: true,
                summary: "{{fields.sectionName}}",
                required: false,
                fields: [
                  { label: Section name, name: sectionName, widget: string, required: false },
                  { label: Disable, name: disable, widget: boolean, required: false },
                  { label: Heading, name: heading, widget: string, required: false },
                  { label: Description, name: description, widget: text, required: false },
                  {
                    label: Decorate,
                    name: decorate,
                    widget: select,
                    required: false,
                    options: [
                      { label: "None", value: "" },
                      { label: "Decorate 1", value: "type1" },
                      { label: "Decorate 2", value: "type2" }
                    ]
                  }
                ]
              },
              {
                label: Supports,
                name: supports,
                widget: object,
                collapsed: true,
                summary: "{{fields.sectionName}}",
                required: false,
                fields: [
                  { label: Section name, name: sectionName, widget: string, required: false },
                  { label: Disable, name: disable, widget: boolean, required: false },
                  { label: Heading, name: heading, widget: string, required: false },
                  { label: Description, name: description, widget: text, required: false },
                  {
                    label: Decorate,
                    name: decorate,
                    widget: select,
                    required: false,
                    options: [
                      { label: "None", value: "" },
                      { label: "Decorate 1", value: "type1" },
                      { label: "Decorate 2", value: "type2" }
                    ]
                  },
                  {
                    label: Body,
                    name: body,
                    widget: list,
                    required: false,
                    fields: [
                      { label: Image, name: image, widget: image },
                      { label: Title, name: title, widget: string },
                      { label: Description, name: description, widget: text },
                      { label: Button Text, name: buttonText, widget: string },
                      { label: Link, name: link, widget: string },
                    ]
                  }
                ]
              },
              {
                label: Zigzag,
                name: zigzag,
                widget: object,
                collapsed: true,
                summary: "{{fields.sectionName}}",
                required: false,
                fields: [
                  { label: Section name, name: sectionName, widget: string, required: false },
                  { label: Disable, name: disable, widget: boolean, required: false },
                  { label: Background color, name: backgroundColor, widget: color, required: false },
                  {
                    label: Body,
                    name: body,
                    widget: object,
                    collapsed: true,
                    required: false,
                    fields: [
                      { label: Image, name: image, widget: string, required: false },
                      { label: Title, name: title, widget: string, required: false },
                      { label: Description, name: description, widget: text, required: false },
                      { label: Reverse, name: reverse, widget: boolean, required: false },
                    ]
                  }
                ]
              }
            ]
          }
      - file: src/pages/pricing/index.md
        label: Pricing
        name: pricing
        fields:
          - {
            label: "Template Key",
            name: "templateKey",
            widget: "hidden",
            default: "pricing-page",
          }
          - {
            label: Plans,
            name: plans,
            widget: object,
            collapsed: true,
            fields: [
              { label: Heading, name: heading, widget: string },
              { label: Description, name: description, widget: text },
              {
                label: Decorate,
                name: decorate,
                widget: select,
                required: false,
                options: [
                  { label: "None", value: "" },
                  { label: "Decorate 1", value: "type1" },
                  { label: "Decorate 2", value: "type2" }
                ]
              },
              {
                label: Body,
                name: body,
                widget: list,
                collapsed: true,
                default: [],
                fields: [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Price, name: price, widget: string },
                  { label: Highlight, name: highlight, widget: boolean, required: false },
                  { label: Button Text, name: buttonText, widget: string },
                  { label: List, name: body, widget: markdown },
                ]
              }
            ]
          }
          - {
            label: Plan comparison,
            name: planComparison,
            widget: object,
            collapsed: true,
            fields: [
              { label: Heading, name: heading, widget: string },
              {
                label: Features,
                name: features,
                widget: list,
                allow_add: false,
                fields: [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: markdown }
                ]
              },
              {
                label: Table,
                name: table,
                widget: list,
                collapsed: true,
                default: [],
                fields: [
                  { label: Title, name: title, widget: string },
                  { label: Price, name: price, widget: string },
                  { label: Highlight, name: highlight, widget: boolean, required: false },
                  { label: Button Text, name: buttonText, widget: string },
                  { label: Content, name: content, widget: markdown }
                ]
              }
            ]
          }
          - {
            label: FAQs,
            name: faqs,
            widget: object,
            collapsed: true,
            fields: [
              { label: Heading, name: heading, widget: string },
              { label: Description, name: description, widget: text },
              {
                label: Decorate,
                name: decorate,
                widget: select,
                required: false,
                options: [
                  { label: "None", value: "" },
                  { label: "Decorate 1", value: "type1" },
                  { label: "Decorate 2", value: "type2" }
                ]
              },
              {
                label: Collapse,
                name: collapse,
                widget: list,
                collapsed: true,
                default: [],
                fields: [
                  { label: Title, name: title, widget: string },
                  { label: Content, name: content, widget: markdown }
                ]
              }
            ]
          }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - {
            label: Decorate,
            name: decorate,
            widget: select,
            required: false,
            options: [
              { label: "None", value: "" },
              { label: "Decorate 1", value: "type1" },
              { label: "Decorate 2", value: "type2" }
            ]
          }
          - {
            label: Form,
            name: form,
            widget: object,
            fields: [
              { label: Name Label, name: nameLabel, widget: string },
              { label: Email Label, name: emailLabel, widget: string },
              { label: Website Label, name: websiteLabel, widget: string },
              { label: Options Label, name: optionsLabel, widget: string },
              {
                label: Option,
                name: "options",
                widget: list,
                fields: [
                  { label: Value, name: value, widget: string }
                ]
              },
              { label: Message Label, name: messageLabel, widget: string },
              { label: Button Text, name: buttonText, widget: string },
            ]
          }
