@include ./files/backend
collections:
  @include ./files/blog
  @include ./files/themes
  - name: "pages"
    label: "Pages"
    files:
      @include ./files/home
      @include ./files/pricing
      @include ./files/about
      @include ./files/contact
